name: PHP CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: ${{ github.ref_name == 'develop' && 'rafaadail/php-ci:7.4.33' || 'rafaadail/php-ci:7.4' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Composer cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Show PHP version
        run: php -v

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests (Laravel if detected)
        run: |
          if [ -f artisan ]; then
            php artisan test
          else
            echo "No Laravel project detected, skipping tests"
          fi